import {analyze,regions,classInfo,riskClassFromScore,greedyPlan,restorationScores,primEdges,routeToTarget,featureCollection,polygon,distanceKm,clamp} from './model.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const format=new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={region:'gobi',custom:false,bounds:{...regions.gobi.bounds},threshold:65,budget:30,years:3,generations:3,effect:60,after:false,step:'risk',scene:'day',is3d:true,selected:null,drawing:false,points:[],tour:false,ready:false};
let analysis,plan,map,route=[],timer,tourFrame,loadingTimer;
const zoneColors=['#87b995','#b4ad79','#a195bd','#769bab','#b58d78','#9aa667'];
function recompute(){analysis=analyze(state.bounds,state);plan=greedyPlan(analysis.cells,state.budget,state.threshold);route=routeToTarget(analysis,plan.selected[0]);if(state.ready)renderLayers();renderSummary();renderResults();if(state.selected!==null)inspectCell(state.selected);}
function point(coords,properties={}){return {type:'Feature',properties,geometry:{type:'Point',coordinates:coords}};}
function line(coords,properties={}){return {type:'Feature',properties,geometry:{type:'LineString',coordinates:coords}};}
function setData(id,data){map.getSource(id)?.setData(data);}
function riskData(){const scores=restorationScores(analysis.cells,plan.selected,state.after?state.effect:0);return featureCollection(analysis.cells.map((c,i)=>polygon(c,{color:classInfo[riskClassFromScore(scores[i])].color,risk:scores[i],zoneColor:zoneColors[c.zone%zoneColors.length]})));}
function renderLayers(){
 setData('cells',riskData());
 const visible=analysis.centers.filter(c=>c.visible);setData('centers',featureCollection(visible.map(c=>point(c.coords,{label:c.label}))));
 setData('network',featureCollection(primEdges(visible).map(e=>line([visible[e.from].coords,visible[e.to].coords]))));
 setData('sites',featureCollection(plan.selected.map((c,i)=>point(c.coords,{index:c.index,rank:i+1}))));
 setData('route',featureCollection(route.length>1?[line(route.map(c=>c.coords))]:[]));
 setData('boundary',featureCollection([polygon({bounds:state.bounds,index:0})]));
 setData('selected',featureCollection(state.selected!==null&&analysis.cells[state.selected]?[polygon(analysis.cells[state.selected])]:[]));
}
function renderSummary(){const scores=restorationScores(analysis.cells,plan.selected,state.after?state.effect:0),areas=[0,0,0,0];let riskArea=0;
 analysis.cells.forEach((c,i)=>{areas[riskClassFromScore(scores[i])]+=c.area;if(scores[i]*100>=state.threshold)riskArea+=c.area;});
 const pct=riskArea/analysis.area*100;$('#risk-percent').innerHTML=`${pct.toFixed(1)}<small>%</small>`;$('#risk-ring-value').style.strokeDasharray=`${201*pct/100} 201`;
 $('#risk-area').textContent=`${format.format(riskArea)} km²`;$('#distribution').innerHTML=areas.map((a,i)=>`<i style="width:${a/analysis.area*100}%;background:${classInfo[i].color}"></i>`).join('');$('#distribution-labels').innerHTML=areas.map((a,i)=>`<span>${classInfo[i].label} ${(a/analysis.area*100).toFixed(0)}%</span>`).join('');$('#selected-count').textContent=plan.selected.length;$('#spent').textContent=`${plan.spent.toFixed(1)} / ${state.budget}억`;$('#budget-track').style.width=`${state.budget?plan.spent/state.budget*100:0}%`;
 const after=restorationScores(analysis.cells,plan.selected,state.effect);const baseline=analysis.cells.reduce((s,c)=>s+c.riskScore*c.area,0)/analysis.area*100,post=analysis.cells.reduce((s,c,i)=>s+after[i]*c.area,0)/analysis.area*100;$('#scenario-delta').textContent=`${baseline.toFixed(2)} → ${post.toFixed(2)}`;
}
function renderResults(){const avg=key=>analysis.cells.reduce((s,c)=>s+c[key]*c.area,0)/analysis.area;const visible=analysis.centers.filter(c=>c.visible);
 const descriptions={risk:['01 · NAIVE BAYES + CA','한 점의 신호에서, 지역의 패턴으로.','6개 합성 환경지표를 베이즈 분류기에 입력하고, 주변 8개 셀의 영향을 반영해 위험 분포를 보정합니다.'],zones:['02 · VORONOI','가장 가까운 거점에, 관리의 책임을.','위·경도에 고정된 가상 거점까지의 지표면 거리로 셀을 배정합니다. 카메라를 움직여도 거점은 같은 위치를 유지합니다.'],plan:['03 · GREEDY','제한된 예산을, 먼저 필요한 곳으로.','위험도·생태가치·주민영향으로 모의 편익을 계산합니다. 비용 대비 편익 순으로 예산 안에서 최대 7개 셀을 선정합니다.'],route:['04 · PRIM + A*','거점에서 현장까지, 연결을 설계하다.','Prim으로 거점 연결 거리의 합을 최소화합니다. A*는 1순위 복원 셀까지 위험과 나지를 고려한 모의 접근 경로를 탐색합니다.']};
 const d=descriptions[state.step];$('#step-tag').textContent=d[0];$('#step-title').textContent=d[1];$('#step-description').textContent=d[2];
 let html='';
 if(state.step==='risk')html=`<div class="result-metric"><span>분석 구역 면적</span><strong>${format.format(analysis.area)}<small>km²</small></strong></div><div class="metric-grid"><div class="metric-tile"><span>평균 식생지수</span><b>${avg('ndvi').toFixed(2)}</b><small>NDVI · 합성값</small></div><div class="metric-tile"><span>평균 토양 수분</span><b>${avg('moisture').toFixed(1)}%</b><small>합성 환경지표</small></div></div><p class="micro">64 × 48 셀 · 8-이웃 · CA ${state.generations}세대</p>`;
 if(state.step==='zones')html=`<div class="result-metric"><span>화면 안의 관리거점</span><strong>${visible.length}<small>곳</small></strong></div><div class="metric-grid"><div class="metric-tile"><span>담당 구역</span><b>${new Set(analysis.cells.map(c=>c.zone)).size}</b><small>외부 인접 거점 포함</small></div><div class="metric-tile"><span>셀 배정</span><b>3,072</b><small>지표면 최단 거리</small></div></div><p class="micro">거점은 실제 시설이 아닙니다. 색은 거점별로 반복될 수 있습니다.</p>`;
 if(state.step==='plan')html=plan.selected.length?`<div class="result-metric"><span>선정 셀 면적</span><strong>${format.format(plan.selected.reduce((s,c)=>s+c.area,0))}<small>km²</small></strong></div>${plan.selected.map((c,i)=>`<button class="rank-row" data-cell="${c.index}"><span class="rank">${i+1}</span><span><strong>복원 후보 ${i+1} · 위험 ${(c.riskScore*100).toFixed(0)}</strong><small>${c.latlng.lat.toFixed(3)}°, ${c.latlng.lng.toFixed(3)}°</small></span><span class="cost">${c.cost.toFixed(1)}억</span></button>`).join('')}<p class="micro">실제 지명에 후보를 임의 대응하지 않고 셀 좌표를 표시합니다.</p>`:`<p class="empty-result">${state.budget===0?'예산이 0억 원입니다. 예산을 늘리면 복원 후보가 표시됩니다.':'예산 안에서 선정할 후보가 없습니다. 예산을 늘리거나 위험 기준을 낮춰보세요.'}</p>`;
 if(state.step==='route'){const edges=primEdges(visible),total=edges.reduce((s,e)=>s+e.distance,0),length=route.reduce((s,c,i)=>i?s+distanceKm(route[i-1].coords,c.coords):s,0);html=`<div class="metric-grid"><div class="metric-tile"><span>거점 연결망</span><b>${format.format(total)}</b><small>km · ${edges.length}개 연결</small></div><div class="metric-tile"><span>1순위 접근 경로</span><b>${route.length?length.toFixed(1):'—'}</b><small>km · ${Math.max(0,route.length-1)}개 격자 이동</small></div></div><p class="micro">${route.length?'가장 가까운 거점에서 출발합니다. 실제 도로·경사·통행 가능 여부는 반영하지 않습니다.':'복원 후보가 없거나 구역 안에 거점이 없어 경로를 표시할 수 없습니다.'}</p>`;}
 $('#result-content').innerHTML=html;$$('[data-cell]').forEach(b=>b.addEventListener('click',()=>{inspectCell(Number(b.dataset.cell));$('.map-stage').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});}));
}
function initMap(){try{if(!window.maplibregl)throw Error('지도 라이브러리를 읽지 못했습니다.');map=new maplibregl.Map({container:'map',center:regions.gobi.center,zoom:6.4,pitch:55,bearing:-15,maxPitch:75,minZoom:2,maxZoom:16,attributionControl:{compact:true},style:{version:8,sources:{satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:18,attribution:'Imagery © Esri, Maxar, Earthstar Geographics'},dem:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],tileSize:256,encoding:'terrarium',maxzoom:15,attribution:'Terrain © Mapzen / AWS & source providers'}},layers:[{id:'background',type:'background',paint:{'background-color':'#283728'}},{id:'satellite',type:'raster',source:'satellite',paint:{'raster-saturation':-.22,'raster-contrast':.12}}]}});
 map.on('load',()=>{map.setTerrain({source:'dem',exaggeration:2});['cells','centers','network','sites','route','boundary','selected','drawing'].forEach(id=>map.addSource(id,{type:'geojson',data:featureCollection()}));
 map.addLayer({id:'risk',type:'fill',source:'cells',paint:{'fill-color':['get','color'],'fill-opacity':.4}});
 map.addLayer({id:'zones',type:'fill',source:'cells',layout:{visibility:'none'},paint:{'fill-color':['get','zoneColor'],'fill-opacity':.46}});
 map.addLayer({id:'boundary',type:'line',source:'boundary',paint:{'line-color':'#d2ec96','line-width':1.4,'line-dasharray':[4,3]}});
 map.addLayer({id:'network',type:'line',source:'network',layout:{visibility:'none'},paint:{'line-color':'#d2ec96','line-width':2,'line-dasharray':[4,3]}});
 map.addLayer({id:'route',type:'line',source:'route',paint:{'line-color':'#8bdfe6','line-width':3}});
 map.addLayer({id:'centers',type:'circle',source:'centers',paint:{'circle-radius':4,'circle-color':'#1a251d','circle-stroke-width':1.5,'circle-stroke-color':'#d2ec96'}});
 map.addLayer({id:'sites',type:'circle',source:'sites',paint:{'circle-radius':8,'circle-color':'#d2ec96','circle-stroke-width':2.5,'circle-stroke-color':'#17261b'}});
 map.addLayer({id:'selected',type:'line',source:'selected',paint:{'line-color':'#ffffff','line-width':2.5}});
 map.addLayer({id:'drawing',type:'circle',source:'drawing',paint:{'circle-radius':7,'circle-color':'#ffffff','circle-stroke-width':2,'circle-stroke-color':'#182719'}});
 state.ready=true;renderLayers();$('#map-status').hidden=true;$('#map-error').hidden=true;clearTimeout(loadingTimer);bindMap();map.setTerrain(state.is3d?{source:'dem',exaggeration:2}:null);map.setPaintProperty('risk','fill-opacity',Number($('#opacity').value)/100);setRegionCamera(false);applyScene();updateLayerVisibility();});
 map.on('error',e=>{if(!state.ready){$('#map-status').textContent='외부 지도 자료를 기다리는 중입니다. 연결 상태를 확인해주세요.';}});
 loadingTimer=setTimeout(()=>{if(!state.ready){$('#map-error').hidden=false;$('#map-error-text').textContent='지도 응답이 지연되고 있습니다. 인터넷 연결 또는 WebGL 지원 상태를 확인해주세요.';}},20000);
 }catch(e){$('#map-error').hidden=false;$('#map-error-text').textContent=e.message;$('#map-status').hidden=true;}}

function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function pressed(button,active){button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));}
function showDialog(){if(!$('#about-dialog').open)$('#about-dialog').showModal();}
function updateLayerVisibility() {if(!state.ready)return;$$('[data-layer]').forEach(input=>map.setLayoutProperty(input.dataset.layer,'visibility',input.checked?'visible':'none'));}
function setStep(step){state.step=step;$$('[data-step]').forEach(b=>pressed(b,b.dataset.step===step));
 const layers={risk:['risk','route'],zones:['zones','network'],plan:['risk','route'],route:['risk','network','route']}[step];$$('[data-layer]').forEach(i=>i.checked=layers.includes(i.dataset.layer));updateLayerVisibility();renderResults();}
function replan(){plan=greedyPlan(analysis.cells,state.budget,state.threshold);route=routeToTarget(analysis,plan.selected[0]);if(state.ready)renderLayers();renderSummary();renderResults();if(state.selected!==null)inspectCell(state.selected);}
function applyScenario(after){state.after=after;pressed($('#before-btn'),!after);pressed($('#after-btn'),after);if(state.ready)setData('cells',riskData());renderSummary();if(state.selected!==null)inspectCell(state.selected);}
function syncControls(){for(const key of ['threshold','budget','years','generations','effect'])$('#'+key).value=state[key];$('#threshold-value').innerHTML=`${state.threshold}<span> / 100</span>`;$('#budget-value').innerHTML=`${state.budget}<span>억 원</span>`;$('#effect-value').textContent=`${state.effect/2}%`;}
function setRegionCamera(animate=true){if(!state.ready)return;stopTour();map.fitBounds([[state.bounds.west,state.bounds.south],[state.bounds.east,state.bounds.north]],{padding:window.innerWidth>850?{top:190,bottom:110,left:50,right:260}:{top:180,bottom:160,left:35,right:45},pitch:state.is3d?55:0,bearing:state.is3d?-15:0,duration:animate&&!reduced.matches?1400:0});}
function regionIdentity(){const r=regions[state.region];$('#region-title').replaceChildren(document.createTextNode(state.custom?'CUSTOM AREA':r.english),Object.assign(document.createElement('span'),{textContent:state.custom?'사용자 지정 구역':r.name}));$('#region-kicker').textContent=state.custom?'직접 선택한 분석 범위':r.sub;$('#area-status').textContent=state.custom?'사용자 지정 구역 · 결과 고정':'선택 구역 고정 · 카메라 이동 시 결과 유지';$$('[data-region]').forEach(b=>pressed(b,!state.custom&&b.dataset.region===state.region));}
function selectRegion(key){cancelDrawing();state.region=key;state.custom=false;state.bounds={...regions[key].bounds};state.selected=null;$('#inspect-panel').hidden=true;regionIdentity();recompute();setRegionCamera();}
function inspectCell(index){const c=analysis.cells[index];if(!c)return;state.selected=index;const chosen=plan.selected.some(p=>p.index===index);const score=c.riskScore*(state.after&&chosen?1-state.effect/200:1);$('#inspect-panel').hidden=false;$('#inspect-title').textContent=chosen?'복원 선정 셀':'선택 셀';$('#cell-id').textContent=c.id;$('#cell-risk').innerHTML=`${(score*100).toFixed(1)}<small>${classInfo[riskClassFromScore(score)].label} · 모의 위험점수</small>`;$('#cell-risk').style.color=classInfo[riskClassFromScore(score)].color;
 const items=[['NDVI',c.ndvi.toFixed(2)],['식생 변화',`${c.ndviTrend.toFixed(1)}%`],['월 강수량',`${c.rainfall.toFixed(1)} mm`],['토양 수분',`${c.moisture.toFixed(1)}%`],['지표 온도',`${c.temperature.toFixed(1)}°C`],['나지 비율',`${c.bareSoil.toFixed(1)}%`],['NB / CA 점수',`${(c.nbRiskScore*100).toFixed(1)} / ${(c.riskScore*100).toFixed(1)}`],['셀 면적',`${c.area.toFixed(2)} km²`],['가상 비용',`${c.cost.toFixed(2)}억 원`]];$('#cell-metrics').innerHTML=items.map(([label,value])=>`<dt>${label}</dt><dd>${value}</dd>`).join('');if(state.ready)setData('selected',featureCollection([polygon(c)]));}
function applyScene(){if(!state.ready)return;const settings={day:[-.22,1,.12],dusk:[.05,.82,.18],night:[-.72,.43,.22]}[state.scene];map.setPaintProperty('satellite','raster-saturation',settings[0]);map.setPaintProperty('satellite','raster-brightness-max',settings[1]);map.setPaintProperty('satellite','raster-contrast',settings[2]);}
function setView(is3d){state.is3d=is3d;pressed($('#view-3d'),is3d);pressed($('#view-2d'),!is3d);$('#terrain-caption').textContent=is3d?'실제 표고 · 높이 2×':'평면 지도 · 지형 강조 없음';if(state.ready){map.setTerrain(is3d?{source:'dem',exaggeration:2}:null);map.easeTo({pitch:is3d?55:0,bearing:is3d?map.getBearing():0,duration:reduced.matches?0:800});}}
function stopTour(){state.tour=false;cancelAnimationFrame(tourFrame);pressed($('#tour-btn'),false);}
function toggleTour(){if(state.tour){stopTour();return;}if(!state.ready)return toast('지도를 불러온 뒤 다시 시도해주세요.');if(reduced.matches)return toast('기기의 동작 줄이기 설정으로 자동 회전이 꺼져 있습니다.');state.tour=true;pressed($('#tour-btn'),true);let prev=performance.now();const tick=now=>{if(!state.tour)return;map.setBearing(map.getBearing()+Math.min(now-prev,50)*.002);prev=now;tourFrame=requestAnimationFrame(tick);};tourFrame=requestAnimationFrame(tick);}
function cancelDrawing(){state.drawing=false;state.points=[];$('#draw-btn').textContent='⌗ 구역 직접 지정';$('#draw-btn').classList.remove('active');if(map){map.getCanvas().style.cursor='';if(state.ready)setData('drawing',featureCollection());}$('#map-status').hidden=state.ready;}
function normalizedBounds(b){if(!Object.values(b).every(Number.isFinite))throw Error('유효한 좌표가 필요합니다.');const width=b.east-b.west,west=((b.west+180)%360+360)%360-180;return {west,east:west+width,south:b.south,north:b.north};}
function setBounds(bounds){try{bounds=normalizedBounds(bounds);const next=analyze(bounds,state);state.bounds={...bounds};state.custom=true;analysis=next;state.selected=null;$('#inspect-panel').hidden=true;regionIdentity();replan();return true;}catch(e){toast(e.message);return false;}}
function bindMap(){
 map.on('click',e=>{if(state.drawing){state.points.push([e.lngLat.lng,e.lngLat.lat]);setData('drawing',featureCollection(state.points.map(p=>point(p))));if(state.points.length===1){$('#map-status').textContent='반대쪽 모서리를 선택해주세요. Esc로 취소할 수 있습니다.';return;}const [a,b]=state.points;const bounds={west:Math.min(a[0],b[0]),east:Math.max(a[0],b[0]),south:Math.min(a[1],b[1]),north:Math.max(a[1],b[1])};if(bounds.east-bounds.west<.005||bounds.north-bounds.south<.005){toast('분석 구역이 너무 작습니다. 두 모서리를 다시 선택해주세요.');state.points=[];setData('drawing',featureCollection());return;}cancelDrawing();if(setBounds(bounds))setRegionCamera();return;}
 const features=map.queryRenderedFeatures(e.point,{layers:['sites']});if(features.length)return inspectCell(Number(features[0].properties.index));const b=state.bounds,lng=e.lngLat.lng+360*Math.round(((b.west+b.east)/2-e.lngLat.lng)/360),lat=e.lngLat.lat;if(lng>=b.west&&lng<=b.east&&lat>=b.south&&lat<=b.north){const col=Math.min(63,Math.floor((lng-b.west)/(b.east-b.west)*64)),row=Math.min(47,Math.floor((b.north-lat)/(b.north-b.south)*48));inspectCell(row*64+col);}});
 map.on('move',()=>{const c=map.getCenter();$('#map-coordinates').textContent=`${Math.abs(c.lat).toFixed(4)}° ${c.lat>=0?'N':'S'}   ${Math.abs(c.lng).toFixed(4)}° ${c.lng>=0?'E':'W'}`;});
 map.on('mousedown',stopTour);map.on('touchstart',stopTour);map.on('wheel',stopTour);
 map.on('error',e=>{if(state.ready&&/tile|fetch|network/i.test(e.error?.message||'')){clearTimeout(timer);$('#map-status').hidden=false;$('#map-status').textContent='일부 배경 자료를 불러오지 못했습니다. 분석값은 합성 데이터입니다.';}});
 map.getCanvas().addEventListener('webglcontextlost',()=>{$('#map-error').hidden=false;$('#map-error-text').textContent='그래픽 연결이 끊겼습니다. 다시 불러오거나 다른 브라우저에서 열어주세요.';});
}
function exportCsv(){const post=restorationScores(analysis.cells,plan.selected,state.effect),selected=new Set(plan.selected.map(c=>c.index));const rows=[['data_type','region','cell_id','latitude','longitude','area_km2','ndvi','ndvi_trend_pct','rainfall_mm','moisture_pct','temperature_c','bare_soil_pct','nb_risk_score','ca_risk_score','scenario_risk_score','selected','virtual_cost_100m_krw','budget_100m_krw','threshold','scenario_reduction_pct']];analysis.cells.forEach((c,i)=>rows.push(['SYNTHETIC_EDUCATIONAL',state.custom?'custom':state.region,c.id,c.latlng.lat,c.latlng.lng,c.area,c.ndvi,c.ndviTrend,c.rainfall,c.moisture,c.temperature,c.bareSoil,c.nbRiskScore,c.riskScore,post[i],selected.has(i),c.cost,state.budget,state.threshold,state.effect/2]));const blob=new Blob(['\ufeff'+rows.map(r=>r.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`LAND15-${state.region}-synthetic.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('합성 데이터 표시가 포함된 CSV를 저장했습니다.');}
async function shareSettings(){const q=new URLSearchParams({region:state.region,budget:String(state.budget),threshold:String(state.threshold),years:String(state.years),ca:String(state.generations),effect:String(state.effect),after:state.after?'1':'0',bounds:[state.bounds.west,state.bounds.south,state.bounds.east,state.bounds.north].map(v=>v.toFixed(7)).join(',')});const url=new URL(location.href);url.search='';url.hash=q.toString();history.replaceState(null,'',url);try{await navigator.clipboard.writeText(url.href);toast('현재 지역·분석 조건·복원 가정이 담긴 링크를 복사했습니다.');}catch{toast('주소창에 설정을 저장했습니다. 주소를 복사해 사용할 수 있습니다.');}}
function restoreSettings(){try{const q=new URLSearchParams(location.hash.slice(1)),region=q.get('region');if(region&&!Object.hasOwn(regions,region))throw Error('지역');if(region){state.region=region;state.bounds={...regions[region].bounds};}
 for(const [key,param,min,max]of [['budget','budget',0,80],['threshold','threshold',20,95],['years','years',1,8],['generations','ca',0,8],['effect','effect',0,100]])if(q.has(param)){const value=Number(q.get(param));if(!Number.isFinite(value)||value<min||value>max)throw Error(param);state[key]=value;}
 if(![1,3,5,8].includes(state.years)||![0,1,3,5,8].includes(state.generations))throw Error('기간');
 if(q.has('bounds')){const values=q.get('bounds').split(',').map(Number);if(values.length!==4||values.some(v=>!Number.isFinite(v)))throw Error('구역');state.bounds=normalizedBounds({west:values[0],south:values[1],east:values[2],north:values[3]});analyze(state.bounds,state);state.custom=Object.keys(state.bounds).some(k=>Math.abs(state.bounds[k]-regions[state.region].bounds[k])>1e-6);}
 state.after=q.get('after')==='1';
 }catch{Object.assign(state,{region:'gobi',custom:false,bounds:{...regions.gobi.bounds},budget:30,threshold:65,years:3,generations:3,effect:60,after:false});toast('유효하지 않은 설정 링크입니다. 기본 고비 시나리오로 시작합니다.');}}
function bindControls(){
 $$('[data-region]').forEach(b=>b.addEventListener('click',()=>selectRegion(b.dataset.region)));$$('[data-layer]').forEach(i=>i.addEventListener('change',updateLayerVisibility));$$('[data-step]').forEach(b=>b.addEventListener('click',()=>setStep(b.dataset.step)));$$('[data-scene]').forEach(b=>b.addEventListener('click',()=>{state.scene=b.dataset.scene;$$('[data-scene]').forEach(v=>pressed(v,v===b));applyScene();}));
 ['threshold','budget'].forEach(key=>$('#'+key).addEventListener('input',e=>{state[key]=Number(e.target.value);syncControls();replan();}));['years','generations'].forEach(key=>$('#'+key).addEventListener('change',e=>{state[key]=Number(e.target.value);recompute();}));
 $('#effect').addEventListener('input',e=>{state.effect=Number(e.target.value);syncControls();applyScenario(state.after);});$('#before-btn').addEventListener('click',()=>applyScenario(false));$('#after-btn').addEventListener('click',()=>applyScenario(true));
 $('#opacity').addEventListener('input',e=>{const value=Number(e.target.value);$('#opacity-value').textContent=`${value}%`;if(state.ready)map.setPaintProperty('risk','fill-opacity',value/100);});
 $('#plan-btn').addEventListener('click',()=>{setStep('plan');$('.analysis-tray').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});});
 for(const id of ['about-btn','sources-btn','method-btn'])$('#'+id).addEventListener('click',showDialog);$('#about-close').addEventListener('click',()=>$('#about-dialog').close());$('#about-dialog').addEventListener('click',e=>{if(e.target===$('#about-dialog')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.target.close();}});
 $('#inspect-close').addEventListener('click',()=>{state.selected=null;$('#inspect-panel').hidden=true;if(state.ready)setData('selected',featureCollection());});
 $('#view-3d').addEventListener('click',()=>setView(true));$('#view-2d').addEventListener('click',()=>setView(false));$('#tour-btn').addEventListener('click',toggleTour);$('#north-btn').addEventListener('click',()=>{stopTour();map?.easeTo({bearing:0,duration:reduced.matches?0:500});});$('#home-btn').addEventListener('click',()=>setRegionCamera());$('#zoom-in').addEventListener('click',()=>{stopTour();map?.zoomIn({duration:reduced.matches?0:300});});$('#zoom-out').addEventListener('click',()=>{stopTour();map?.zoomOut({duration:reduced.matches?0:300});});
 $('#fullscreen-btn').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('.map-stage').requestFullscreen)await $('.map-stage').requestFullscreen();else return toast('이 브라우저는 전체 화면을 지원하지 않습니다.');map?.resize();}catch{toast('전체 화면 전환을 사용할 수 없습니다.');}});document.addEventListener('fullscreenchange',()=>map?.resize());
 $('#draw-btn').addEventListener('click',()=>{if(!state.ready)return toast('지도를 불러온 뒤 구역을 지정해주세요.');if(state.drawing)return cancelDrawing();stopTour();state.drawing=true;state.points=[];$('#draw-btn').textContent='지정 취소 · Esc';$('#draw-btn').classList.add('active');map.getCanvas().style.cursor='crosshair';$('#map-status').hidden=false;$('#map-status').textContent='분석할 사각 구역의 첫 번째 모서리를 선택해주세요.';});
 $('#viewport-btn').addEventListener('click',()=>{if(!state.ready)return toast('지도를 불러온 뒤 다시 시도해주세요.');cancelDrawing();const b=map.getBounds();if(setBounds({west:b.getWest(),south:b.getSouth(),east:b.getEast(),north:b.getNorth()}))toast('현재 화면을 새 분석 구역으로 고정했습니다.');});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.drawing)cancelDrawing();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTour();});reduced.addEventListener('change',()=>{if(reduced.matches)stopTour();});
 $('#reset-btn').addEventListener('click',()=>{Object.assign(state,{threshold:65,budget:30,years:3,generations:3,effect:60,after:false});syncControls();applyScenario(false);setView(true);selectRegion('gobi');setStep('risk');state.scene='day';$$('[data-scene]').forEach(b=>pressed(b,b.dataset.scene==='day'));applyScene();$('#opacity').value=40;$('#opacity-value').textContent='40%';if(state.ready)map.setPaintProperty('risk','fill-opacity',.4);history.replaceState(null,'',location.pathname+location.search);toast('고비 기본 시나리오로 돌아왔습니다.');});$('#retry-btn').addEventListener('click',()=>location.reload());$('#export-btn').addEventListener('click',exportCsv);$('#share-btn').addEventListener('click',shareSettings);
}
function registerAgentTools(){if(!document.modelContext?.registerTool)return;const lifecycle=new AbortController();const tools=[
 {name:'read_land15_analysis',title:'LAND:15 분석 읽기',description:'Read the active synthetic region, budget, risk threshold and selected restoration cells.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {dataType:'synthetic_educational',region:state.custom?'custom':state.region,bounds:state.bounds,budget:state.budget,threshold:state.threshold,spent:plan.spent,selected:plan.selected.map(c=>({id:c.id,coordinates:c.coords,risk:c.riskScore,cost:c.cost}))};}},
 {name:'configure_land15_scenario',title:'LAND:15 복원 시나리오 설정',description:'Change the visible region, virtual budget and threshold, then calculate a synthetic restoration plan.',inputSchema:{type:'object',properties:{region:{type:'string',enum:Object.keys(regions)},budget:{type:'integer',minimum:0,maximum:80},threshold:{type:'integer',minimum:20,maximum:95}},required:['region','budget','threshold'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['region','budget','threshold'].includes(k))||!Object.hasOwn(regions,input.region)||!Number.isInteger(input.budget)||input.budget<0||input.budget>80||!Number.isInteger(input.threshold)||input.threshold<20||input.threshold>95)throw Error('Invalid LAND:15 scenario');state.budget=input.budget;state.threshold=input.threshold;syncControls();selectRegion(input.region);setStep('plan');return {dataType:'synthetic_educational',region:state.region,budget:state.budget,threshold:state.threshold,spent:plan.spent,selectedCount:plan.selected.length};}}
 ];for(const tool of tools)try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
restoreSettings();syncControls();bindControls();recompute();regionIdentity();pressed($('#before-btn'),!state.after);pressed($('#after-btn'),state.after);initMap();registerAgentTools();
