import test from 'node:test';
import assert from 'node:assert/strict';
import {createCameraSession,cameraErrorMessage} from './hand-camera.mjs';
function fixture(getUserMedia){const video={srcObject:null,play:async()=>{},pause(){}};return {video,session:createCameraSession({video,mediaDevices:{getUserMedia}})};}
function stream(){const track={stops:0,stop(){this.stops++;},addEventListener(type,callback){this.ended=callback;}};return {track,getTracks:()=>[track],getVideoTracks:()=>[track]};}
test('camera requests video only after explicit start and releases tracks',async()=>{let options;const s=stream(),{session,video}=fixture(async o=>(options=o,s));assert.equal(options,undefined);assert.equal(await session.start(),true);assert.equal(options.audio,false);assert.equal(options.video.facingMode,'user');assert.equal(video.srcObject,s);session.stop();assert.equal(s.track.stops,1);assert.equal(video.srcObject,null);});
test('cancel while permission is pending releases a late camera stream',async()=>{let resolve;const s=stream(),{session,video}=fixture(()=>new Promise(r=>resolve=r));const pending=session.start();session.stop();resolve(s);assert.equal(await pending,false);assert.equal(s.track.stops,1);assert.equal(video.srcObject,null);});
test('stale permission resolution cannot replace a newer session',async()=>{const resolvers=[],old=stream(),current=stream(),{session,video}=fixture(()=>new Promise(r=>resolvers.push(r)));const a=session.start(),b=session.start();resolvers[1](current);assert.equal(await b,true);resolvers[0](old);assert.equal(await a,false);assert.equal(video.srcObject,current);assert.equal(old.track.stops,1);session.dispose();assert.equal(current.track.stops,1);});
test('video playback failure closes camera immediately',async()=>{const s=stream(),{session,video}=fixture(async()=>s);video.play=async()=>{throw new Error('playback failed');};await assert.rejects(session.start(),/playback failed/);assert.equal(s.track.stops,1);assert.equal(video.srcObject,null);});
test('camera track interruption clears video and reports ended',async()=>{let ended=0;const s=stream(),video={play:async()=>{},pause(){}};const session=createCameraSession({video,mediaDevices:{getUserMedia:async()=>s},onEnded:()=>ended++});await session.start();s.track.ended();assert.equal(ended,1);assert.equal(session.isActive(),false);assert.equal(video.srcObject,null);});
test('dispose prevents restart and rejects no additional permission requests',async()=>{let calls=0;const {session}=fixture(async()=>{calls++;return stream();});session.dispose();await assert.rejects(session.start(),/disposed/);assert.equal(calls,0);});
test('permission/device errors provide actionable messages without leaking raw errors',()=>{assert.match(cameraErrorMessage({name:'NotAllowedError'}),/권한/);assert.match(cameraErrorMessage({name:'NotFoundError'}),/웹캠/);assert.match(cameraErrorMessage({name:'NotReadableError'}),/다른 앱/);assert.doesNotMatch(cameraErrorMessage({message:'secret device details'}),/secret/);});
